"""Narrow interfaces between server modules (for typing and clear boundaries)."""

from __future__ import annotations

from typing import Any, Dict, Protocol, Tuple

from models import ClientSession


class SessionPort(Protocol):
    """Outbound TCP messaging and lobby snapshots."""

    async def handle_login(self, client: ClientSession, message: Dict[str, Any]) -> None: ...

    async def send(self, client: ClientSession, message: Dict[str, Any]) -> None: ...

    async def send_error(self, client: ClientSession, code: str, message: str) -> None: ...

    async def broadcast_rooms_to_lobby(self) -> None: ...

    async def send_rooms_snapshot(self, client: ClientSession) -> None: ...


class RoomPort(Protocol):
    """Room lifecycle and in-room gameplay entry points."""

    async def handle_create_room(self, client: ClientSession) -> None: ...

    async def handle_join_room(self, client: ClientSession, message: Dict[str, Any]) -> None: ...

    async def handle_leave_room(self, client: ClientSession) -> None: ...

    async def handle_state_update(self, client: ClientSession, message: Dict[str, Any]) -> None: ...

    async def forward_to_room(self, client: ClientSession, message: Dict[str, Any]) -> None: ...

    async def handle_player_hit(self, client: ClientSession, message: Dict[str, Any]) -> None: ...

    async def handle_player_fall(self, client: ClientSession, message: Dict[str, Any]) -> None: ...

    async def handle_drop_collected(self, client: ClientSession, message: Dict[str, Any]) -> None: ...

    async def handle_drop_collision(self, client: ClientSession, message: Dict[str, Any]) -> None: ...

    async def handle_tile_break(self, client: ClientSession, message: Dict[str, Any]) -> None: ...

    async def handle_floating_coin_collected(self, client: ClientSession, message: Dict[str, Any]) -> None: ...


class UdpPort(Protocol):
    async def handle_datagram(self, data: bytes, addr: Tuple[str, int]) -> None: ...
